const DATA=[
{title:'Astilladoras',headline:'Convierte los residuos en un recurso de valor.',body:[`Las astilladoras Vermeer están construidas para el trabajo diario, con soluciones que facilitan la operación, optimizan el rendimiento y contribuyen a la seguridad del operador.`,`Diseñadas para paisajistas, municipios y empresas de mantenimiento, permiten procesar ramas y troncos de diámetro pequeño hasta 19” de manera eficiente, reduciendo el volumen de residuos y facilitando su aprovechamiento como mulch, composta o biomasa.`],close:'Más productividad. Menos residuos. Más valor para tu operación.',dir:'astilladoras',count:3},
{title:'Trituradoras',headline:'Transforma grandes volúmenes de residuos en material aprovechable.',body:[`Las trituradoras Vermeer combinan construcción robusta, potencia y versatilidad para enfrentar operaciones de gran escala, desde desmonte y procesamiento de residuos municipales hasta producción de composta.`,`Su variedad de configuraciones permite elegir la capacidad, potencia y equipamiento adecuados para cada proyecto, ayudándote a maximizar la productividad y aprovechar mejor cada jornada de trabajo.`],close:'Soluciones para procesar más, trabajar mejor y generar mayor valor.',dir:'trituradoras',count:3},
{title:'Zanjadoras de disco',headline:'Abre camino a tu próximo proyecto.',body:[`Las zanjadoras de tractor Vermeer combinan potencia, precisión y versatilidad para trabajar en una amplia variedad de condiciones, desde entornos urbanos y residenciales hasta terrenos con roca.`,`Una solución eficiente para la instalación de fibra óptica, electricidad, agua, drenaje y otros servicios subterráneos.`],close:'Elige el equipo y accesorio adecuados para las condiciones reales de tu proyecto.',dir:'zanjadoras-disco',count:3},
{title:'Zanjadoras de cadena',headline:'Una zanja. Una infraestructura. Un proyecto que tiene que avanzar.',body:[`Las zanjadoras Vermeer están diseñadas para afrontar una amplia variedad de aplicaciones: agua, gas, electricidad, fibra óptica, alcantarillado, drenaje y distribución de tuberías, entre otras.`,`Desde terrenos blandos hasta condiciones más exigentes con roca y materiales abrasivos, Vermeer ofrece diferentes equipos y configuraciones para adaptarse a las necesidades de cada obra.`],close:'La productividad comienza con elegir correctamente el equipo.',dir:'zanjadoras-cadena',count:3},
{title:'Perforación Horizontal Direccional (HDD)',headline:'Instala bajo tierra. Avanza sobre ella.',body:[`Las perforadoras direccionales horizontales Vermeer ofrecen una solución eficiente para instalar infraestructura subterránea reduciendo la intervención sobre la superficie.`,`Diseñadas para aplicaciones como fibra óptica, telecomunicaciones, energía, agua, gas y tuberías de diferentes diámetros, combinan potencia, precisión y tecnología para enfrentar los retos de cada proyecto.`,`Detrás de cada equipo está el respaldo Vermeer: asesoría especializada, capacitación, servicio, mantenimiento y refacciones para ayudarte a mantener tu operación en movimiento.`],close:'Tu proyecto tiene condiciones específicas. Tu equipo también debería tenerlas.',dir:'hdd',count:3},
{title:'Minería de superficie',headline:'Potencia para operaciones de gran escala.',body:[`Equipos de alto tonelaje diseñados para el arranque, trituración y transferencia directa de materiales en minas a cielo abierto y grandes obras de infraestructura.`,`Ofrecen una alternativa eficiente, segura y de bajo impacto ambiental frente a los métodos tradicionales de voladura, optimizando el costo por tonelada extraída.`],close:'',dir:'mineria',count:2}];
let cat=0,slide=0,timer; const $=s=>document.querySelector(s);
const WA_BASE='https://wa.me/528135507673?text=';
const WA_GENERIC='Hola, vi la página de Maquinaria Especializada y me gustaría recibir información y cotizar un equipo Vermeer.';
function waUrl(message){return WA_BASE+encodeURIComponent(message)}
function setGeneralWhatsApp(){
  document.querySelectorAll('.floating-wa,.wa-line').forEach(a=>a.href=waUrl(WA_GENERIC));
}
setGeneralWhatsApp();

const tabs=$('#tabs'),slides=$('#slides'),select=$('#equipmentSelect');
DATA.forEach((d,i)=>{const b=document.createElement('button');b.className='tab';b.textContent=d.title;b.onclick=()=>renderCategory(i);tabs.appendChild(b);const o=document.createElement('option');o.value=d.title;o.textContent=d.title;select.appendChild(o)}); let other=document.createElement('option');other.value='Otro / No estoy seguro';other.textContent='Otro / No estoy seguro';select.appendChild(other);
function renderCategory(i){cat=i;slide=0;const d=DATA[i];document.querySelectorAll('.tab').forEach((t,j)=>t.classList.toggle('active',j===i));$('#catNum').textContent=String(i+1).padStart(2,'0');$('#catTitle').textContent=d.title;$('#catHeadline').textContent=d.headline;$('#catBody').innerHTML=d.body.map(p=>`<p>${p}</p>`).join('');$('#catClose').textContent=d.close;slides.innerHTML='';for(let n=1;n<=d.count;n++){const el=document.createElement('div');el.className='slide'+(n===1?' active':'');el.innerHTML=`<img src="assets/images/${d.dir}/${d.dir}-${n}.webp" alt="${d.title} Vermeer ${n}" loading="${n===1?'eager':'lazy'}">`;slides.appendChild(el)}$('#total').textContent=String(d.count).padStart(2,'0');$('#current').textContent='01';document.querySelector('.floating-wa').href=categoryWhatsApp();resetTimer()}
function move(dir){const ss=[...document.querySelectorAll('.slide')];ss[slide].classList.remove('active');slide=(slide+dir+ss.length)%ss.length;ss[slide].classList.add('active');$('#current').textContent=String(slide+1).padStart(2,'0');resetTimer()}
function resetTimer(){clearInterval(timer);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)timer=setInterval(()=>move(1),5000)}
$('.prev').onclick=()=>move(-1);$('.next').onclick=()=>move(1);let x=0;$('.gallery').addEventListener('touchstart',e=>x=e.touches[0].clientX,{passive:true});$('.gallery').addEventListener('touchend',e=>{let d=e.changedTouches[0].clientX-x;if(Math.abs(d)>45)move(d<0?1:-1)},{passive:true});document.querySelectorAll('.quote-link').forEach(a=>a.onclick=()=>select.value=DATA[cat].title);
function categoryWhatsApp(){return waUrl(`Hola, vi la página de Maquinaria Especializada y me gustaría recibir información y cotizar ${DATA[cat].title} Vermeer para mi proyecto.`)}
renderCategory(0);window.addEventListener('scroll',()=>$('#nav').classList.toggle('scrolled',scrollY>30));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
const menuBtn=document.querySelector('.menu'), mobileMenu=document.querySelector('.mobile-menu');
menuBtn?.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));mobileMenu.setAttribute('aria-hidden',String(!open));});
mobileMenu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');mobileMenu.setAttribute('aria-hidden','true');}));
$('#leadForm').addEventListener('submit',()=>{$('#formNote').textContent='Enviando solicitud…';});
